# Generated by Django 2.0.4 on 2018-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180422_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
