# Generated by Django 2.0.4 on 2018-04-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180422_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
