# Generated by Django 2.0.4 on 2018-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180425_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
